name: four_cuts
description: A photo card creation app similar to 인생넷컷

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  camera: ^0.11.1
  image: ^4.1.3
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  freezed: ^3.0.4
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true